// <auto-generated />
namespace AllYouMedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AspNetUser_PhotoIMG : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AspNetUser_PhotoIMG));
        
        string IMigrationMetadata.Id
        {
            get { return "201808071925241_AspNetUser_PhotoIMG"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
