// <auto-generated />
namespace AllYouMedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UserCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201809090645495_UserCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
