// <auto-generated />
namespace AllYouMedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class genre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genre));
        
        string IMigrationMetadata.Id
        {
            get { return "201902241000136_genre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
