// <auto-generated />
namespace AllYouMedia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ismembeshipcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ismembeshipcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201902180440375_ismembeshipcategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
